wandb_version: 1

env_name:
  desc: null
  value: navigation
model_path:
  desc: null
  value: null
render:
  desc: null
  value: false
log_std:
  desc: null
  value: -0.0
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.95
l2_reg:
  desc: null
  value: 0.001
learning_rate:
  desc: null
  value: 3.0e-05
randomization:
  desc: null
  value: 1
adaptation:
  desc: null
  value: 1
depth_prediction_model:
  desc: null
  value: dpt
clip_epsilon:
  desc: null
  value: 0.2
hist_length:
  desc: null
  value: 5
num_threads:
  desc: null
  value: 1
seed:
  desc: null
  value: 1
min_batch_size:
  desc: null
  value: 2048
eval_batch_size:
  desc: null
  value: 0
max_iter_num:
  desc: null
  value: 200
log_interval:
  desc: null
  value: 1
save_model_interval:
  desc: null
  value: 5
gpu_index:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.39.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710974004.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.16.4
      6: 4.39.0.dev0
      8:
      - 5
      13: linux-x86_64
